on:
  push:
    branches:
      - main
env:
  PACKAGE_NAME: pycode_info
  OWNER: Justusdecker

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        
        with:
          python-version: '3.x'
      
  setup-and-build:
    runs-on: ubuntu-latest
    needs : test
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install flake8

      - name: Install build and twine
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: python -m build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Get Version number
        id: get_version
        run: |
          PVERSION="versions.env"
          echo "VERSION=$(python -c 'import src.pycode_info; print(src.pycode_info.__version__)')" >> $GITHUB_ENV
      - name: Create GitHub Release
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo $PVERSION
          gh release create v${{ env.PACKAGE_NAME }}-$VERSION --title "${{ env.PACKAGE_NAME }}-v${{ env.VERSION }}" --notes "Automated release of version ${{ env.PACKAGE_NAME }}-${{ env.VERSION }}" --draft=false --prerelease=false